Fix eslint errors
Lul-Abdifan/Capstone-Project1 pull request #3
Opened 2022-10-27 23:06 UTC by Lul-Abdifan

# The Files are:
  -  Add Index.html for the home page
  -  Add about.html for the about page
  -  Add script.js for the whole javascript code
  -  Add a style.css file for styling the home page and the about page
  -  Add an assets  folder that contains all the images of the website
  -  Add Linters setup for checking errors in the code
  -  Fix occurred errors
# What may differ :
-  Do a mobile menu for the home page
- Do mobile menu for about page
- Add More and Less buttons to add and remove dynamically generated objects
# Github Tasks
-  Deploy the website
- Update the Readme file and make it professional
- Add MIT License
# Short Presentation video
-  [See Demo video](https://www.loom.com/share/b51c3e9eba57445d964476b6d7b3d197)

2022-10-28 00:08 UTC, emmiiorji requested changes
Hi @Lul-Abdifan, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with node_modules folder not ignored properly. In addition to not being professional, it is difficult to comment on some files.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-28 08:10 UTC, Lul-Abdifan commented
@emmiiorji  Thank you for your careful feedback. I appreciate your work .Happy Coding :smile: :+1: :

2022-10-28 10:22 UTC, mwanawabangona requested changes
Hi @Lul-Abdifan 

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 10:22 UTC, mwanawabangona commented on index.html
> -
- [ ] `required`
- [ ] Amazing job so far 👏 
- [ ] the text is overlapping please see to it that it is staying the boxes a the origin design
- [ ] also the `join conference button` is not responsive please make reponsive

- [ ] `your template`
![image](https://user-images.githubusercontent.com/66230306/198561678-a6603926-1dfb-4193-a97b-a19d9698ead3.png)
![image](https://user-images.githubusercontent.com/66230306/198563082-ac3804ad-50aa-448a-9fb5-28f2d5994405.png)



`origin design`
![mainspeaker](https://user-images.githubusercontent.com/66230306/198561232-a52eabf8-cefd-488a-8ddc-17b750c64a33.png)

2022-10-28 10:22 UTC, mwanawabangona commented on index.html
>      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
- [ ] `required`
- [ ] Also the speaker section is not very responsive you can see from the background color and the overlapping text.
- [ ] Please see screenshots below. 🥂 

`your template`
![image](https://user-images.githubusercontent.com/66230306/198564133-b2d4d9bb-e347-4ec8-b076-c83a0af5040b.png)

`origin design`
![image](https://user-images.githubusercontent.com/66230306/198564360-e061b76a-67dd-49a2-b5bc-f20eef667e3d.png)

2022-10-28 13:48 UTC, Lul-Abdifan commented
#  Required Chenges are Done
-  Update Partners section more responsive
-   Update Speakers section more responsive
-   Update Join The coming Conference button more responsive
-   Fix overlapping texts
### Note:
-  For speaker since I used many words for position and description It won't be more beautiful unless removing many words. If you have any question. I am here @Lul-Abdifan

2022-10-28 15:36 UTC, Munsa1 requested changes
Hi @Lul-Abdifan, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] Due to insufficient files I will leave a comment here
- [ ] Kindly follow the given design for the `see projects` section
Your design
![image](https://user-images.githubusercontent.com/81932478/198674483-352f832e-509d-4753-a685-8508e9fd2c77.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/198674799-6ad9380c-03d9-4792-b5e6-09bee16e202b.png)

- [ ] The top section does not follow the given template, kindly follow the given template.The section has a `hx` heading, paragraph and  a logo

Given template
![image](https://user-images.githubusercontent.com/81932478/198675277-77709310-dce6-4817-b39e-324fa4b59651.png)

Your design
![image](https://user-images.githubusercontent.com/81932478/198675392-d394775c-809a-4af3-a471-f68ec787a4b5.png)

- [ ] Your top section is missing the `contact` information section, kindly add this.

Your design
![image](https://user-images.githubusercontent.com/81932478/198676883-5b51891e-c12c-495c-964f-5eaca0aff9e5.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/198676980-31dc36dd-d44f-4fdc-9d92-1eeb8432801a.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 22:33 UTC, Lul-Abdifan commented
## Required Changes are Done
-  Add contact  information section
-  Update about   page totally
-  Add logo for about page

2022-10-28 23:42 UTC, Gopxfs approved these changes
# 🟢 STATUS: APPROVED 🟢

## Hello @Lul-Abdifan 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ You added the contact information on the `about` page.
✔️ Removed the additional picture on the `see projects` section.
✔️ Added a header, a paragraph, and a logo to the about section! Perfect!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 07:59 UTC, merged

2022-10-29 08:06 UTC, Lul-Abdifan commented
@emmiiorji  Thank you for your constructive feedback.:smile::smile:

2022-10-29 08:06 UTC, Lul-Abdifan commented
@Gopxfs Thank you for your constructive feedback.:smile::smile:

2022-10-29 08:06 UTC, Lul-Abdifan commented
@Gopxfs  Thank you for your constructive feedback.:smile::smile:

2022-10-29 08:07 UTC, Lul-Abdifan commented
@mwanawabangona  Thank you for your constructive feedback.:smile::smile:

2022-10-29 08:07 UTC, Lul-Abdifan commented
@Munsa1 Thank you for your constructive feedback.:smile::smile: